var res = {
  HealTexture_png: "res/Heal_texture.png",
  DotTexture_png: "res/Dot_texture.png",
  particle_texture: "res/Dot_texture.png",
  chara_princessselect_10: "res/char/chara_princessselect_10.png",
  chara_princessselect_11: "res/char/chara_princessselect_11.png",
  chara_princessselect_12: "res/char/chara_princessselect_12.png",
  ss_BattleScene_bg1: "res/field/ss_BattleScene_bg1.jpg",
  ss_BattleScene_bg2: "res/field/ss_BattleScene_bg2.jpg",
  ss_BattleScene_bg3: "res/field/ss_BattleScene_bg3.jpg",
  chara_enemy_1: "res/char/chara_enemy_1.png",
  chara_enemy_2: "res/char/chara_enemy_2.png",
  chara_enemy_3: "res/char/chara_enemy_3.png",
  chara_enemy_4: "res/char/chara_enemy_4.png",
  chara_enemy_5: "res/char/chara_enemy_5.png",
  chara_enemy_6: "res/char/chara_enemy_6.png",
  chara_enemy_7: "res/char/chara_enemy_7.png",
  FireTexture0_plist: "res/effect/Fire_texture0.plist",
  FireTexture1_plist: "res/effect/Fire_texture1.plist",
  FireTexture2_plist: "res/effect/Fire_texture2.plist",
  FireTexture3_plist: "res/effect/Fire_texture3.plist",
  FireTexture4_plist: "res/effect/Fire_texture4.plist",
  WaterTexture1_plist: "res/effect/Water_texture1.plist",
  WaterTexture2_plist: "res/effect/Water_texture2.plist",
  WaterTexture3_plist: "res/effect/Water_texture3.plist",
  WaterTexture4_plist: "res/effect/Water_texture4.plist",
  WoodTexture1_plist: "res/effect/Wood_texture1.plist",
  WoodTexture2_plist: "res/effect/Wood_texture2.plist",
  WoodTexture3_plist: "res/effect/Wood_texture3.plist",
  WoodTexture4_plist: "res/effect/Wood_texture4.plist",
  HealTexture1_plist: "res/effect/Heal_texture1.plist",
  SlipTexture1_plist: "res/effect/Slip_texture1.plist",
  YamiTexture1_plist : "res/effect/particle_texturehosi1.plist",
  YamiTexture21_plist : "res/effect/particle_texturehosi2.plist",
  YamiTexture31_plist : "res/effect/particle_texturehosi3.plist",
  YamiTexture41_plist : "res/effect/particle_texturehosi4.plist",
  YamiTexture51_plist : "res/effect/particle_texturehosi5.plist",
  YamiTexture61_plist : "res/effect/particle_textureyami6.plist",
  YamiTexture72_plist : "res/effect/particle_textureyamitame.plist",
  //闇魔法出すほう
  YamiTexture83_plist : "res/effect/yamimahou1_texture.plist",
  YamiTexture93_plist : "res/effect/yamimahou2_texture (1).plist",
  YamiTexture103_plist : "res/effect/yamimahou3_texture (1).plist",
  YamiTexture113_plist : "res/effect/yamimahou4_texture (1).plist",
  YamiTexture123_plist : "res/effect/yamimahou5_texture (1).plist",
  YamiTexture133_plist : "res/effect/yamimahou6_texture (1).plist",
  YamiTexture143_plist : "res/effect/yamimahou7_texture (1).plist",
  YamiTexture153_plist : "res/effect/yamimahou8_texture (1).plist",
  YamiTexture163_plist : "res/effect/yamimahou9_texture (1).plist",
  particleTexture171_plist : "res/effect/particle_effect1.plist",
  particleTexture181_plist : "res/effect/particle_effect1-2.plist",
  particleTexture192_plist : "res/effect/particle_effect2.plist",
  particleTexture202_plist : "res/effect/particle_effect2-2.plist",
  particleTexture213_plist : "res/effect/particle_effect3.plist",
  particleTexture223_plist : "res/effect/particle_effect3-2.plist",
  particleTexture233_plist : "res/effect/particle_effect3-3.plist",
  particleTexture243_plist : "res/effect/particle_effect3-4.plist",


};

var g_resources = [];
for (var i in res) {
  g_resources.push(res[i]);
}
